CREATE TABLE PersistentLogs (
    Id INT PRIMARY KEY IDENTITY,
    Timestamp DATETIME NOT NULL,
    EntityType NVARCHAR(50) NOT NULL,
    ActionType NVARCHAR(50) NOT NULL,
    PerformedBy NVARCHAR(255) NOT NULL,
    Details NVARCHAR(MAX)
);
