ALTER TABLE `Colaboradores`
ADD COLUMN `Setor` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `Ramal` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `Alarme` VARCHAR(100) NULL DEFAULT NULL,
ADD COLUMN `Videoporteiro` VARCHAR(100) NULL DEFAULT NULL;
