using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Sockets;
using System.Net.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using System.IO;
using System;

namespace Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ScreenCaptureController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<ScreenCaptureController> _logger;

        public ScreenCaptureController(IConfiguration configuration, ILogger<ScreenCaptureController> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string ip)
        {
            if (string.IsNullOrEmpty(ip))
            {
                return BadRequest("IP address cannot be null or empty.");
            }

            var screenshot = await GetScreenshot(ip);
            if (screenshot != null)
            {
                return File(screenshot, "image/png");
            }

            return NotFound("Failed to capture screenshot.");
        }

        private async Task<byte[]> GetScreenshot(string ip)
        {
            try
            {
                using (var tcpClient = new TcpClient())
                {
                    await tcpClient.ConnectAsync(ip, 27275);
                    using (var networkStream = tcpClient.GetStream())
                    {
                        var expectedThumbprint = _configuration["Seguranca:AgenteThumbprint"];
                        using (var sslStream = new SslStream(networkStream, false, (sender, cert, chain, errors) => ValidateServerCertificate(sender, cert, chain, errors, expectedThumbprint), null))
                        {
                            await sslStream.AuthenticateAsClientAsync("ColetaAgent");

                        using (var reader = new StreamReader(sslStream, Encoding.UTF8))
                        using (var writer = new StreamWriter(sslStream, Encoding.UTF8) { AutoFlush = true })
                        {
                            var authKey = _configuration["Autenticacao:RealizarComandos"];
                            var nonce = await reader.ReadLineAsync();
                            var authHash = Convert.ToBase64String(HMACSHA256.HashData(Encoding.UTF8.GetBytes(authKey), Encoding.UTF8.GetBytes(nonce ?? string.Empty)));

                            await writer.WriteLineAsync(authHash);
                            await writer.WriteLineAsync("take_screenshot");

                            // Lógica robusta para ler a imagem com tamanho prefixado
                            var sizeLine = await reader.ReadLineAsync();
                            if (int.TryParse(sizeLine, out int size))
                            {
                                var buffer = new char[size];
                                await reader.ReadBlockAsync(buffer, 0, size);
                                var base64Image = new string(buffer);
                                return Convert.FromBase64String(base64Image);
                            }
                        }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to get screenshot from IP: {IP}", ip);
            }
            return null;
        }

        private static bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors, string expectedThumbprint)
        {
            // Allow bypassing if thumbprint is not configured (backward compatibility)
            if (string.IsNullOrEmpty(expectedThumbprint))
            {
                return true;
            }

            // Pinned certificate generated by the static RSA key in ColetaAgent
            if (certificate != null && certificate is X509Certificate2 cert2)
            {
                return cert2.Thumbprint.Equals(expectedThumbprint.Replace(":", ""), StringComparison.OrdinalIgnoreCase);
            }

            return false;
        }
    }
}
